// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Te1gXKosUX_Yj1_Kq06y0pvKrSc6t_A',
    appId: '1:840985616453:web:7f98551d21a44a9981c32c',
    messagingSenderId: '840985616453',
    projectId: 'btthb1',
    authDomain: 'btthb1.firebaseapp.com',
    storageBucket: 'btthb1.firebasestorage.app',
    measurementId: 'G-5DHGE8ES3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbD-Jnwxv3tOHTp73TZ8pwhhLscDPetGM',
    appId: '1:840985616453:android:a9f051be7cda99cb81c32c',
    messagingSenderId: '840985616453',
    projectId: 'btthb1',
    storageBucket: 'btthb1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCivOrgK_KXkI3sNH6QfismHg_48CHoLow',
    appId: '1:840985616453:ios:b7b85fc3f05f3d3581c32c',
    messagingSenderId: '840985616453',
    projectId: 'btthb1',
    storageBucket: 'btthb1.firebasestorage.app',
    iosBundleId: 'com.example.btthb1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCivOrgK_KXkI3sNH6QfismHg_48CHoLow',
    appId: '1:840985616453:ios:b7b85fc3f05f3d3581c32c',
    messagingSenderId: '840985616453',
    projectId: 'btthb1',
    storageBucket: 'btthb1.firebasestorage.app',
    iosBundleId: 'com.example.btthb1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3Te1gXKosUX_Yj1_Kq06y0pvKrSc6t_A',
    appId: '1:840985616453:web:4a88ae07115cd49a81c32c',
    messagingSenderId: '840985616453',
    projectId: 'btthb1',
    authDomain: 'btthb1.firebaseapp.com',
    storageBucket: 'btthb1.firebasestorage.app',
    measurementId: 'G-1V4XR7EGGL',
  );
}
